# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asr.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'asr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\" \n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"\x1d\n\rTranscription\x12\x0c\n\x04text\x18\x01 \x01(\t24\n\x03\x41SR\x12-\n\nTranscribe\x12\x0b.AudioChunk\x1a\x0e.Transcription(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=13
  _globals['_AUDIOCHUNK']._serialized_end=45
  _globals['_TRANSCRIPTION']._serialized_start=47
  _globals['_TRANSCRIPTION']._serialized_end=76
  _globals['_ASR']._serialized_start=78
  _globals['_ASR']._serialized_end=130
# @@protoc_insertion_point(module_scope)
